// const sampleproducts = [
//     {
//         name: "Pre-Workout Powder",
//         description: "Boost your energy and focus before hitting the gym",
//         image: "https://th.bing.com/th/id/OIP.eLNEAgFUTCDedj3t_YEHHwHaFq?pid=ImgDet&rs=1",
//         price: 350,
//         type: "supplements",
//         availability: "15 left",
//         review: "Gives me the kick I need before my workouts",
//     },
//    {
//     name:"Skipping Rope",
//     description:"used for skipping",
//     image:"https://gymmanufacturer.in/wp-content/uploads/2019/07/Skipping-Rope.jpg",
//     price:200,
//     type:"cardio",
//     availability:"10 left",
//     review:"Good quality",
//    },
//     {
//         name: "Gym Duffel Bag",
//         description: "Spacious and durable bag for your gym essentials",
//         image: "image_url_here",
//         price: 40,
//         type: "Accessories",
//         availability: "15 left",
//         review: "Fits everything I need for the gym and more",
//     },
//     {
//         name: "Wrist Wraps (Pair)",
//         description: "Provide wrist support for heavy lifts and workouts",
//         image: "image_url_here",
//         price: 15,
//         type: "Accessories",
//         availability: "30 left",
//         review: "Keeps my wrists stable during intense lifts",
//     },
//     {
//         name: "Running Shoes (Men's/Women's)",
//         description: "High-quality running shoes for superior comfort and performance",
//         image: "image_url_here",
//         price: 80,
//         type: "Footwear",
//         availability: "Various sizes available",
//         review: "Perfect for both casual runs and marathons",
//     },
//     {
//         name: "Compression Socks (Pair)",
//         description: "Improve circulation and reduce muscle fatigue during workouts",
//         image: "image_url_here",
//         price: 20,
//         type: "Accessories",
//         availability: "25 pairs left",
//         review: "A game-changer for long training sessions",
//     },
//     {
//         name: "Protein Powder",
//         description: "High-quality protein for muscle recovery and growth",
//         image: "image_url_here",
//         price: 45,
//         type: "supplements",
//         availability: "20 left",
//         review: "Tastes great and helps me build muscle",
//     },
//     {
//         name: "Creatine Monohydrate Powder",
//         description: "Improve strength and endurance for intense workouts",
//         image: "image_url_here",
//         price: 20,
//         type: "supplements",
//         availability: "30 left",
//         review: "A must for strength training",
//     },
//     {
//         name: "Omega-3 Fish Oil Softgels",
//         description: "Support heart health and joint mobility",
//         image: "image_url_here",
//         price: 15,
//         type: "supplements",
//         availability: "25 left",
//         review: "Keeps me feeling great",
//     },
//     {
//         name: "Vitamin D3 Supplements",
//         description: "Boost immune health and bone strength",
//         image: "image_url_here",
//         price: 10,
//         type: "supplements",
//         availability: "35 left",
//         review: "Essential for overall well-being",
//     },
//     {
//         name: "Amino Acid Blend",
//         description: "Support muscle recovery and growth with essential amino acids",
//         image: "image_url_here",
//         price: 25,
//         type: "supplements",
//         availability: "15 left",
//         review: "Helps me bounce back after tough workouts",
//     },
//     {
//         name: "Stationary Exercise Bike",
//         description: "A comfortable, low-impact cardio machine for home workouts",
//         image: "image_url_here",
//         price: 300,
//         type: "Cardio",
//         availability: "10 left",
//         review: "Great for indoor cycling workouts",
//     },
//     {
//         name: "Kettlebell Set (3 Kettlebells)",
//         description: "Versatile kettlebells for strength and endurance training",
//         image: "image_url_here",
//         price: 50,
//         type: "Strength",
//         availability: "25 left",
//         review: "Perfect for full-body workouts",
//     },
//     {
//         name: "Resistance Bands Kit (11-Piece)",
//         description: "Various resistance levels for a wide range of exercises",
//         image: "image_url_here",
//         price: 30,
//         type: "Strength",
//         availability: "20 left",
//         review: "A complete home gym in one kit",
//     },
//     {
//         name: "Adjustable Dumbbells (Pair)",
//         description: "Space-saving, adjustable dumbbells for home workouts",
//         image: "image_url_here",
//         price: 150,
//         type: "Strength",
//         availability: "10 left",
//         review: "Convenient and easy to use",
//     },
//     {
//         name: "Multi-Purpose Gym Bench",
//         description: "Sturdy bench for various strength training exercises",
//         image: "image_url_here",
//         price: 80,
//         type: "Strength",
//         availability: "15 left",
//         review: "Solid and comfortable for workouts",
//     },
//     {
//         name: "High-Waisted Yoga Pants",
//         description: "Stylish and comfortable pants for yoga and athleisure",
//         image: "image_url_here",
//         price: 35,
//         type: "Apparel",
//         availability: "30 left",
//         review: "My go-to for yoga and relaxation",
//     },
//     {
//         name: "Fitness Tracker Watch",
//         description: "Monitor your fitness goals and health metrics",
//         image: "image_url_here",
//         price: 60,
//         type: "Accessories",
//         availability: "25 left",
//         review: "Tracks everything I need for my workouts",
//     },
//     {
//         name: "Weight Lifting Gloves",
//         description: "Protect your hands and improve grip during workouts",
//         image: "image_url_here",
//         price: 20,
//         type: "Accessories",
//         availability: "40 left",
//         review: "A must for weightlifting sessions",
//     },
//     {
//         name: "Insulated Water Bottle",
//         description: "Keep your drinks cold or hot during workouts",
//         image: "image_url_here",
//         price: 15,
//         type: "Accessories",
//         availability: "50 left",
//         review: "Stylish and practical",
//     },
//     {
//         name: "Extra-Thick Exercise Mat",
//         description: "Cushioned mat for yoga, Pilates, and floor exercises",
//         image: "image_url_here",
//         price: 25,
//         type: "Accessories",
//         availability: "20 left",
//         review: "Comfortable and durable",
//     }
// ];
// module.exports={data:sampleproducts};

const sampleproducts = [

    {
        name: "5kg Dumbell",
        description: "The Flexibell is the latest innovation in Home Fitness, replacing multiple sets of weights. 1 Flexibell is equivalent to 15 different dumbbells. The product has easy-to-use selection dials for adjusting weights.",
        image:"https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_300,h_400,ar_0.75,c_fill,q_70/dpr_1.5/cultgear-content/cv4GCjuUxcgr5AABQAt1qdCQ",
        price: 750,
        type: "Strength",
        availability: "25 left",
        review: "It lets me hit arms workout like never before",
    },
    {
        name: "Kettlebell",
        description: "Kettlebell exercises often involve several muscle groups at once, making them a highly effective way to give your arms, legs, and abs a great workout in a short amount of time. They can improve both your strength and your cardiovascular fitness.",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6oy1_H8eTzT5xuqoS5LgUEIhU_neT_yAOIraoGbDlWvw9BL3Nr86NVJ10jYWydlHdBAw&usqp=CAU",
        price: 650,
        type: "Strength",
        availability: "15 left",
        review: "Kettlebell has a good grip and a wide range of sizes",
    },

    {
        name: "Barbell",
        description: "No other equipment allows such dramatic improvements in overall strength. Start out using a weight you’re comfortable with, increase the load every week and watch your numbers fly up.",
        image:"https://m.media-amazon.com/images/I/41NZyBUa-lL.jpg",
        price: 850,
        type: "Strength",
        availability: "10 left",
        review: "High quality product and it is very durable",
    },

    {
        name: "jumprope",
        description: "Skipping rope is the best cardio exercise as it increases the heart rate. This will significantly reduce the risk of heart diseases and stroke.",
        image: "https://m.media-amazon.com/images/I/61VqnE79V2L.jpg",
        price: 400,
        type: "Cardio",
        availability: "10 left",
        review: "Great for a quick indoor cardio exercise",
    },
    {
        name: "benches",
        description: "Sturdy,safeand made of leather ",
        image: "https://www.theflexnest.com/cdn/shop/products/Benchfinal_1080x.jpg?v=1639229095",
        price: 400,
        type: "Cardio",
        availability: "17 left",
        review: "Perfect for doing glutes workouts",
    },
    {
        name: "pull up bars",
        description: "Sturdy,safe and high durability ",
        image: "https://m.media-amazon.com/images/I/71N2N1akPwL._AC_UL480_FMwebp_QL65_.jpg",
        price: 400,
        type: "Cardio",
        availability: "17 left",
        review: "Sturdy with a very good grip ",
    },
    {
        name: "core sliders",
        description: "Sturdy,safe and high durability ",
        image: "https://img.fruugo.com/product/5/57/622670575_max.jpg",
        price: 700,
        type: "Cardio",
        availability: "17 left",
        review: "high durability product  ",
    },

    {
        name: "Racks and cages",
        description: "Sturdy,safe and high durability ",
        image: "https://m.media-amazon.com/images/I/51tyWEVlB4L._AC._SR360,460.jpg",
        price: 700,
        type: "Cardio",
        availability: "17 left",
        review: "high durability product  ",
    },
    {
        name: "treadmill",
        description: "Sturdy,safe and high durability ",
        image: "https://v.fastcdn.co/u/db28084b/61790081-0-Smart-run-1.png",
        price: 700,
        type: "Cardio",
        availability: "17 left",
        review: "high durability product  ",
    },
    {
        name: "Assault bike",
        description: "Sturdy,safe and high durability ",
        image: "https://cdn-images.cure.fit/www-curefit-com/image/upload/fl_progressive,f_auto,q_auto:eco,w_500,ar_3:4,c_fill/dpr_2/cultgear-content/gZNKESJuEE5QqZFaCVeZjx8h",
        price: 700,
        type: "Cardio",
        availability: "17 left",
        review: "high durability product  ",
    },
    {
        name: "Step machine",
        description: "Sturdy,safe and high durability ",
        image: "https://5.imimg.com/data5/SELLER/Default/2023/5/308380990/DQ/NO/ND/60633516/stair-stepper-machine-500x500.png",
        price: 700,
        type: "Cardio",
        availability: "17 left",
        review: "high durability product  ",
    },
    {
        name: "Bigmuscles Protein Powder",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://m.media-amazon.com/images/I/61d6UfDdpsL._SL1200_.jpg",
        price: 35,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {
        name: "ATOM Whey Protein Powder",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://m.media-amazon.com/images/I/71mBvhlzBRL._SY879_.jpg'",
        price: 35,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {
        name: "Almond Protein Bar",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://m.media-amazon.com/images/I/618ReTqzmPL._SX679_.jpg",
        price: 35,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {
        name: "Vegan Plant Protein Powder",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://m.media-amazon.com/images/I/71mBvhlzBRL._SY879_.jpg",
        price: 35,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {
        name: "MB Protein Bar",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://m.media-amazon.com/images/I/71YVLXZRUaL._SX679_PIbundle-6,TopRight,0,0_AA679SH20_.jpg",
        price: 35,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {
        name: "Unibic Snack bar",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://m.media-amazon.com/images/I/51xQDwKC1-L._SX300_SY300_QL70_FMwebp_.jpg",
        price: 35,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {
        name: "Mypro Sport Nutrition",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://m.media-amazon.com/images/I/71irjc91MoL._SY879_.jpg",
        price: 35,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {
        name: "MuscleBlaze Protein Shake",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://m.media-amazon.com/images/I/715KFAQslPL._SX679_.jpg",
        price: 35,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {
        name: "Herbalife Protein Shake",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://m.media-amazon.com/images/I/6128c8J0vSL._SY879_.jpg",
        price: 35,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },

    {
        name: "Nike mens Air max sport shoes",
        description: "High-quality running shoes for superior comfort and performance",
        image: "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1556130360-vaporfly-4-flyknit-running-shoe-v7G3FB.jpg?crop=0.915xw:0.488xh;0.0449xw,0.322xh",
        price: 80,
        type: "Footwear",
        availability: "Various sizes available",
        review: "Perfect for both casual runs and marathons",
    },
    {
        name: "Nike womans sneakers",
        description: "High-quality running shoes for superior comfort and performance",
        image: "\https://www.tennisnuts.com/images/product/full/WMNS-NIKE-LUNARTEMPO-2-818098_500_C_PREM.jpg",
        price: 80,
        type: "Footwear",
        availability: "Various sizes available",
        review: "Perfect for both casual runs and marathons",
    },
    {
        name: "Nike pegasis Mens running shoes",
        description: "High-quality running shoes for superior comfort and performance",
        image: "https://cdnd.lystit.com/photos/821b-2014/12/02/nike-gray-mens-flex-experience-run-3-wide-running-sneakers-from-finish-line-product-1-25645138-2-977232122-normal.jpeg",
        price: 80,
        type: "Footwear",
        availability: "Various sizes available",
        review: "Perfect for both casual runs and marathons",
    },
    {
        name: "Nike Mens grey jersey",
        description: "Stylish and comfortable pants for yoga and athleisure",
        image: "https://cdnb.lystit.com/photos/2011/09/14/nike-carbon-heather-black-pro-combat-dri-fit-fitted-t-shirt-product-2-1987374-078852542.jpeg'",
        price: 35,
        type: "Apparel",
        availability: "30 left",
        review: "My go-to for yoga and relaxation",
    },
    {
        name: "Nike Womens sweatshirt",
        description: "Stylish and comfortable pants for yoga and athleisure",
        image: "https://www.lifestylesports.com/on/demandware.static/-/Sites-LSS_eCommerce_Master/default/dwb36aba66/images/64585813xlarge.jpg ",
        price: 35,
        type: "Apparel",
        availability: "30 left",
        review: "My go-to for yoga and relaxation",
    },
    {
        name: "Nike mens Sleveless shirt",
        description: "Stylish and comfortable pants for yoga and athleisure",
        image: "https://cdnb.lystit.com/photos/nike/be0d8fd5/nike-WhiteBlackBlack-Pro-Mens-Sleeveless-Training-Top.jpeg",
        price: 35,
        type: "Apparel",
        availability: "30 left",
        review: "My go-to for yoga and relaxation",
    },
    {
        name: "Nike leggings for women",
        description: "Stylish and comfortable pants for yoga and athleisure",
        image: "'https://i.pinimg.com/originals/b0/81/38/b0813856830cb3fdd659f44ca0a0cfdc.jpg",
        price: 35,
        type: "Apparel",
        availability: "30 left",
        review: "My go-to for yoga and relaxation",
    },
    {
        name: "Nike joggers for men",
        description: "Stylish and comfortable pants for yoga and athleisure",
        image: "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto/f2bf2a2d-562a-46dc-9023-885cbc7b53a8/sportswear-club-fleece-mens-joggers-KflRdQ.jpg",
        price: 35,
        type: "Apparel",
        availability: "30 left",
        review: "My go-to for yoga and relaxation",
    },
    {
        name: "Nike joggers for women",
        description: "Stylish and comfortable pants for yoga and athleisure",
        image: "https://img.style-factory.net/nike-ladies-912877-2.jpg",
        price: 35,
        type: "Apparel",
        availability: "30 left",
        review: "My go-to for yoga and relaxation",
    },
    {
        name: "Pre-Workout Powder",
        description: "Boost your energy and focus before hitting the gym",
        image: "https://tse2.mm.bing.net/th?id=OIP.pwur1iAV_fct8-CrJqAHMQHaHa&pid=Api&P=0&h=180",
        price: 35,
        type: "supplements",
        availability: "15 left",
        review: "Gives me the kick I need before my workouts",
    },
    {
        name: "Gym Duffel Bag",
        description: "Spacious and durable bag for your gym essentials",
        image: "https://tse4.mm.bing.net/th?id=OIP.0tFX43UgjDIN2bUh2dKS_QHaHa&pid=Api&P=0&h=180",
        price: 40,
        type: "Accessories",
        availability: "15 left",
        review: "Fits everything I need for the gym and more",
    },
    {
        name: "Wrist Wraps (Pair)",
        description: "Provide wrist support for heavy lifts and workouts",
        image: "https://tse1.mm.bing.net/th?id=OIP.12ThVzC_uMp9cS4hzpg_OgHaHa&pid=Api&P=0&h=180",
        price: 15,
        type: "Accessories",
        availability: "30 left",
        review: "Keeps my wrists stable during intense lifts",
    },
    {
        name: "Running Shoes (Men's/Women's)",
        description: "High-quality running shoes for superior comfort and performance",
        image: "https://tse2.mm.bing.net/th?id=OIP.KRbOWMC9SWx__aEuUO1tBgAAAA&pid=Api&P=0&h=180",
        price: 80,
        type: "Footwear",
        availability: "Various sizes available",
        review: "Perfect for both casual runs and marathons",
    },
    {
        name: "Compression Socks (Pair)",
        description: "Improve circulation and reduce muscle fatigue during workouts",
        image: "https://i.insider.com/5b60cbade199f31b008b4851?format=jpeg",
        price: 20,
        type: "Accessories",
        availability: "25 pairs left",
        review: "A game-changer for long training sessions",
    },
    {
        name: "Protein Powder",
        description: "High-quality protein for muscle recovery and growth",
        image: "https://tse3.mm.bing.net/th?id=OIP.0A3lBHUhPCN4q-nmpE4shQHaHa&pid=Api&P=0&h=180",
        price: 45,
        type: "supplements",
        availability: "20 left",
        review: "Tastes great and helps me build muscle",
    },
    {
        name: "Creatine Monohydrate Powder",
        description: "Improve strength and endurance for intense workouts",
        image: "https://i5.walmartimages.com/asr/fa178d77-ed2b-4c15-bb0f-f63a911bcfbc_2.2fa923bd6fa338427f77545c08a73a77.png",
        price: 20,
        type: "supplements",
        availability: "30 left",
        review: "A must for strength training",
    },
    {
        name: "Omega-3 Fish Oil Softgels",
        description: "Support heart health and joint mobility",
        image: "https://i5.walmartimages.com/asr/8a1be5a3-8b5d-4e14-a5d6-4802df2e52a8.8a1599e5f4b2ac8ea90c43c1a57b2046.jpeg",
        price: 15,
        type: "supplements",
        availability: "25 left",
        review: "Keeps me feeling great",
    },
    {
        name: "Vitamin D3 Supplements",
        description: "Boost immune health and bone strength",
        image: "https://i5.walmartimages.com/asr/a8d98710-370e-4bc5-8fd4-04c0ec7adf9d.8c15b50c4e6178d65181f5510e177eca.jpeg",
        price: 10,
        type: "supplements",
        availability: "35 left",
        review: "Essential for overall well-being",
    },
    {
        name: "Amino Acid Blend",
        description: "Support muscle recovery and growth with essential amino acids",
        image: "https://res.cloudinary.com/du8msdgbj/image/upload/l_watermark_346,w_690,h_700/a_ignore,w_690,h_700,c_pad,q_auto,f_auto/v1534399068/aor9mtxcama2ly2ta3q8.png",
        price: 25,
        type: "supplements",
        availability: "15 left",
        review: "Helps me bounce back after tough workouts",
    },
    {
        name: "Stationary Exercise Bike",
        description: "A comfortable, low-impact cardio machine for home workouts",
        image: "https://i5.walmartimages.com/asr/4894db9c-66ec-4ae6-a734-99fcaf3b076a_1.c40dc02c041478b51f29f9f7dbf87f41.jpeg?odnWidth=1000&odnHeight=1000&odnBg=ffffff",
        price: 300,
        type: "Cardio",
        availability: "10 left",
        review: "Great for indoor cycling workouts",
    },
    {
        name: "Kettlebell Set (3 Kettlebells)",
        description: "Versatile kettlebells for strength and endurance training",
        image: "https://res-5.cloudinary.com/s247/image/upload/c_pad,dpr_1.0,f_auto,q_auto/media/catalog/product/c/o/confidence_pro_3pc_kettlebell_set_main.jpg",
        price: 50,
        type: "Strength",
        availability: "25 left",
        review: "Perfect for full-body workouts",
    },
    {
        name: "Resistance Bands Kit (11-Piece)",
        description: "Various resistance levels for a wide range of exercises",
        image: "https://erp.ener-j.co.uk/web/image/product.image/1842/image?unique=28b5ec9",
        price: 30,
        type: "Strength",
        availability: "20 left",
        review: "A complete home gym in one kit",
    },
    {
        name: "Adjustable Dumbbells (Pair)",
        description: "Space-saving, adjustable dumbbells for home workouts",
        image: "https://i5.walmartimages.com/asr/0d2b0aec-3c0d-49d0-a112-e28d70d36703.509188299c485ce14310c65825a8cbe2.jpeg?odnWidth=1000&odnHeight=1000&odnBg=ffffff",
        price: 150,
        type: "Strength",
        availability: "10 left",
        review: "Convenient and easy to use",
    },
    {
        name: "Multi-Purpose Gym Bench",
        description: "Sturdy bench for various strength training exercises",
        image: "https://tse4.mm.bing.net/th?id=OIP._IcjW7bkY2I3K-efcO7wcwHaGy&pid=Api&P=0&h=180",
        price: 80,
        type: "Strength",
        availability: "15 left",
        review: "Solid and comfortable for workouts",
    },
    {
        name: "High-Waisted Yoga Pants",
        description: "Stylish and comfortable pants for yoga and athleisure",
        image: "https://tse4.mm.bing.net/th?id=OIP.2n3IHSVGUgPMJ3h4ORIoywHaJo&pid=Api&P=0&h=180",
        price: 35,
        type: "Apparel",
        availability: "30 left",
        review: "My go-to for yoga and relaxation",
    },
    {
        name: "Fitness Tracker Watch",
        description: "Monitor your fitness goals and health metrics",
        image: "https://i5.walmartimages.com/asr/4b66716f-0d57-4018-8854-7dcfcbd39c3c_1.a7f2f17d2c06f878e2d1279089e7dcdf.jpeg",
        price: 60,
        type: "Accessories",
        availability: "25 left",
        review: "Tracks everything I need for my workouts",
    },
    {
        name: "Weight Lifting Gloves",
        description: "Protect your hands and improve grip during workouts",
        image: "https://tse2.mm.bing.net/th?id=OIP.uOQ3d0IhuyJObiGFkNVR1gHaFm&pid=Api&P=0&h=180",
        price: 20,
        type: "Accessories",
        availability: "40 left",
        review: "A must for weightlifting sessions",
    },
    {
        name: "Insulated Water Bottle",
        description: "Keep your drinks cold or hot during workouts",
        image: "https://images-na.ssl-images-amazon.com/images/I/71yd3F-wi2L._AC_SL1500_.jpg",
        price: 15,
        type: "Accessories",
        availability: "50 left",
        review: "Stylish and practical",
    },
    {
        name: "Extra-Thick Exercise Mat",
        description: "Cushioned mat for yoga, Pilates, and floor exercises",
        image: "https://tse4.mm.bing.net/th?id=OIP.XU831OYXe0MciLOTCThPuQHaEL&pid=Api&P=0&h=180",
        price: 25,
        type: "Accessories",
        availability: "20 left",
        review: "Comfortable and durable",
    }
];
module.exports={data:sampleproducts};